# Generated by Django 2.2.7 on 2020-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='user_url',
            field=models.URLField(),
        ),
    ]
